name: CI Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies & build
        working-directory: GitAction
        run: mvn -B clean package

      - name: Run unit tests
        working-directory: GitAction
        run: mvn test

      - name: Commit build artifacts
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"
          git add .
          git commit -m "CI: build artifacts [skip ci]" || echo "Nothing to commit"
          git push
